del /q /s packages\boost_1_%BOOST_VERSION%_0\*.exe
del /q /s packages\boost_1_%BOOST_VERSION%_0\user-confg.jam
rd /q /s packages\boost_1_%BOOST_VERSION%_0\bin.v2
rd /q /s packages\cairo
rd /q /s packages\expat
rd /q /s packages\freetype
rd /q /s packages\gdal
rd /q /s packages\harfbuzz
rd /q /s packages\harfbuzz-build
rd /q /s packages\icu
rd /q /s packages\jpeg
rd /q /s packages\libpng
rd /q /s packages\libtiff
rd /q /s packages\libxml2
rd /q /s packages\pixman
rd /q /s packages\postgresql
rd /q /s packages\proj
rd /q /s packages\protobuf
rd /q /s packages\sqlite
rd /q /s packages\webp
rd /q /s packages\zlib