@ECHO OFF
SETLOCAL
SET EL=0
ECHO ------------- COPY MAPNIK DEBUG SYMBOLS ---------

IF NOT DEFINED ROOTDIR (ECHO ROOTDIR not defined && SET ERRORLEVEL=1 && GOTO ERROR)
IF NOT DEFINED PKGDIR (ECHO PKGDIR not defined && SET ERRORLEVEL=1 && GOTO ERROR)
IF NOT DEFINED DEPSDIR (ECHO DEPSDIR not defined && SET ERRORLEVEL=1 && GOTO ERROR)
IF NOT DEFINED PACKAGEDEBUGSYMBOLS (ECHO PACKAGEDEBUGSYMBOLS not defined && SET ERRORLEVEL=1 && GOTO ERROR)
IF NOT DEFINED MAPNIK_SDK (ECHO MAPNIK_SDK not defined && SET ERRORLEVEL=1 && GOTO ERROR)

SET DEST_LIBDIR=%MAPNIK_SDK%\lib\
SET DEST_INPUTDIR=%MAPNIK_SDK%\lib\mapnik\input\
SET SRC_MAPNIKBIN=%PKGDIR%\mapnik-%MAPNIKBRANCH%\mapnik-gyp\build\%BUILD_TYPE%

::mapnik itself
COPY /Y %SRC_MAPNIKBIN%\_mapnik.pdb %DEST_LIBDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\mapnik.pdb %DEST_LIBDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
::mapnik input plugins
COPY /Y %SRC_MAPNIKBIN%\csv.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\gdal.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\geojson.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\ogr.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\pgraster.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\postgis.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\raster.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\shape.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\sqlite.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
COPY /Y %SRC_MAPNIKBIN%\topojson.pdb %DEST_INPUTDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR


ECHO ----------- TODO CAIRO

COPY /Y %PKGDIR%\expat\%PLATFORMX%\%BUILD_TYPE%\expat.pdb %DEST_LIBDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

ECHO ----------- TODO FREETYPE

COPY /Y %PKGDIR%\expat\%PLATFORMX%\%BUILD_TYPE%\expat.pdb %DEST_LIBDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

COPY /Y %PKGDIR%\gdal\gdal%GDAL_VERSION_FILE%.pdb %DEST_LIBDIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR



GOTO DONE

:ERROR
ECHO ---------- ERROR COPY MAPNIK DEBUG SYMBOLS --------------
ECHO ERRORLEVEL %ERRORLEVEL%
SET EL=%ERRORLEVEL%

:DONE
echo ---------- DONE COPY MAPNIK DEBUG SYMBOLS --------------
EXIT /b %EL%
